version: '3.8'

services:
  sqlserver:
    build: .
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${SQL_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-U", "sa", "-P", "${SQL_PASSWORD}", "-d", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10